### PR TITLE
Make the sw imports sorted

### LINKED ISSUE #1972: workbox-webpack-plugin hash bug
**Library Affected**:
*workbox-webpack-plugin*

**Browser & Platform**:
*all browsers*

**Issue or Feature Request Description**:
`getManifestEntriesFromCompilation` returns an unsorted list of entries. This causes unnecessary change on the hash used by `precacheManifest` file.

### PR DESCRIPTION
**Pull request by el**
R: @jeffposnick @philipwalton

Fixes #1972

*Description of what's changed/fixed.*
Added sorting before generating a hash

### CODE REVIEW

**Comment by el** [comment]
I signed it!

**Comment by jeffposnick** [comment]
We unfortunately need to update the hashes hardcoded in the unit tests when there's a change that alters the webpack plugin's output.

I'll push a commit to the branch in this PR with the necessary updates.

**Comment by el** [comment]
Thanks for handling the tests. Can you publish a new version to npm? (We have a package layout file that lists all the files and this makes precache file change the name randomly)

**Comment by jeffposnick** [comment]
Likely within the next week or so—we do try to batch up the changes a bit in between releases.

**Comment by el** [comment]
Ohh, that works thanks. I will just disable the chunks until then ;)

**Pull request merged**
