### PR TITLE
update rollup/plugin-terser

### PR DESCRIPTION
**Pull request by kadirosmanust**
**Prior to creating a pull request, please follow all the steps in the [contributing guide](https://github.com/GoogleChrome/workbox/blob/v6/CONTRIBUTING.md).**

Fixes #_issue number_

_Description of what's changed/fixed._

### CODE REVIEW

**Review by adarshmadrecha — APPROVED** [review]
Perfect.

**Comment by adarshmadrecha** [comment]
This is needed, or else it creates this warning.
image

**Comment by kadirosmanust** [comment]
@adarshmadrecha  That's why I added  "@rollup/plugin-terser": "^0.2.1" to package.json

**Review by TemaSM — APPROVED** [review]

**Comment by ansidev** [comment]
@KadoRaw You should update the description since it follows the contribution rules.

**Comment by ansidev** [comment]
@KadoRaw The package version should be updated too.

**Comment by tropicadri** [comment]
Fixed in #3170

**Pull request closed without merging**
