### PR TITLE
fix(rollup-plugin): replace package rollup-plugin-terser by @rollup/plugin-terser

### LINKED ISSUE #3136: deprecated rollup-plugin-terser@7.0.2
**Library Affected**:
workbox-build

**Issue or Feature Request Description**:
deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

### PR DESCRIPTION
**Pull request by ansidev**
**Prior to creating a pull request, please follow all the steps in the [contributing guide](https://github.com/GoogleChrome/workbox/blob/v6/CONTRIBUTING.md).**

Fixes #3136, #3144

_Description of what's changed/fixed._

- Replaces the package `rollup-plugin-terser` by `@rollup/plugin-terser` since `rollup-plugin-terser` is deprecated.

### CODE REVIEW

**Comment by Jppnp** [comment]
now workbox-build@6.5.4 still use rollup-plugin-terser

**Review by Jppnp — APPROVED** [review]

**Review by Jppnp — APPROVED** [review]
May be done

**Review by rivajunior — APPROVED** [review]

**Comment by Artur-** [comment]
Could this be merged now that there is a workbox 7, @tropicadri ?

**Comment by ansidev** [comment]
Rebased onto v7!

**Comment by alangdm** [comment]
Any chance we could see this get merged?
I'm getting errors using tools that depend on this package that have already removed the deprecated terser

**Comment by ansidev** [comment]
It seems that maintainers are laid-off 🙃

**Comment by thepassle** [comment]
This is also causing issues for consumers of rollup-plugin-workbox apparently, so indeed would be great to get this merged :)

**Review by kennarddh — APPROVED** [review]

**Comment by DamianGlowala** [comment]
@philipwalton, please? 🙏

**Comment by davidtranjs** [comment]
Please help to check this PR, it would help a lot 🥺

**Review by TemaSM — APPROVED** [review]

**Comment by pwbriggs** [comment]
> Fixes #3136, #3144

Also fixes #3142, #3154, #3200, and #3228. @googlechrome @jeffposnick @philipwalton can someone please merge this PR?

**Review by t-montes — APPROVED** [review]
Applies the fix correctly:
This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

**Review by Lure5134 — APPROVED** [review]

**Review by AFCMS — APPROVED** [review]

**Review by smirnoffmv — APPROVED** [review]

**Review by Chevindu — APPROVED** [review]

**Comment by Ten-Taken** [comment]
Would love to see a fix as well. I think this is now causing issues with rollup's dynamic imports. I suspect an unpinned dependency in the older rollup repos.

**Comment by ansidev** [comment]
I guess Google does not care about this project anymore, the latest commit is pushed 10 months ago.

**Review by hellohejinyu — APPROVED** [review]

**Review by DysektAI — APPROVED** [review]

**Review by tropicadri — APPROVED** [review]

**Pull request merged**
