### PR TITLE
Use await/async inside of build:update-cdn-details

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani  @addyosmani @gauntface

Switching to the promise-based `readJSON()`/`writeJSON()` and using `await`/`async` inside the task seems to have cleared up the task completion issues I was seeing.

### CODE REVIEW

**Comment by addyosmani** [comment]
screenshot_20171012-131400

Hmm. Failing on AppVeyor atm.

**Comment by jeffposnick** [comment]
That's fixed by https://github.com/GoogleChrome/workbox/pull/884

**Comment by addyosmani** [comment]
Approved https://github.com/GoogleChrome/workbox/pull/884. This one LGTM if we can get AV passing again :)

**Comment by jeffposnick** [comment]
I'm merging this one first as I now see that AppVeyor in #884 didn't complete due to this 😄

**Pull request merged**
