### PR TITLE
Add Typescript type definitions for workbox-sw

### LINKED ISSUE #1410: Link to TypeScript definitions for workbox-sw
**Library Affected**:
workbox-sw

**Browser & Platform**:
all browsers

**Issue or Feature Request Description**:
Please add TypeScript support. 😃

https://github.com/GoogleChrome/workbox/issues/217 ended with [this](https://github.com/GoogleChrome/workbox/issues/217#issuecomment-306899129):
> Gonna close this until someone requests it.

So perhaps this can be the "official" request.

### PR DESCRIPTION
**Pull request by wessberg**
R: @jeffposnick @addyosmani @gauntface

Fixes #1410 

This PR adds Typescript type definitions for `workbox-sw` and provides them from the `types` property of the package.json of that package.

The type declarations are complete and based on [the reference docs](https://developers.google.com/web/tools/workbox/reference-docs/latest/).

Also, during linting, ESLint complained about a few invalid JSDoc comments in some other files, so I've also fixed those.

### CODE REVIEW

**Comment by wessberg** [comment]
CLA has been signed

**Comment by prateekbh** [comment]
Also, just and fyi and to check if there is no collision between the two.

The TS for workbox generateSW options is here: https://github.com/Polymer/polymer-build/pull/309

**Comment by wessberg** [comment]
@prateekbh There are no collisions between the two 😊. [Your typings](https://github.com/prateekbh/polymer-build/blob/c474601697ca60e1ec5b2849df3a4753b512151a/custom_typings/workbox.d.ts) cover `workbox-build` whereas these strictly cover `workbox-sw` and related namespaces.

**Comment by arkhamvm** [comment]
It's will be great! Any news about adding?

**Comment by wessberg** [comment]
I added typings for streams such that the typings fully support v3.2.0

**Comment by josephliccini** [comment]
Awesome to see TypeScript support!!

Though, I think there might be a bug in these:
image

Shouldn't it be `Promise<Response> | undefined`, _not_ `Promise<Response | undefined>`?

**Comment by josephliccini** [comment]
Also, it would be cool if we could get an interface for custom plugins to implement that would have the type checking enabled.  It would basically enforce that any plugins are of this shape: https://developers.google.com/web/tools/workbox/guides/using-plugins#custom_plugins

**Comment by josephliccini** [comment]
Here are the plugin typings:
```ts
// Custom type for Officehome
declare interface WorkboxPlugin {
    readonly cacheWillUpdate?: (context: CacheWillUpdatePluginContext) => Response
    readonly cacheDidUpdate?: (context: CacheDidUpdatePluginContext) => void;
    readonly cachedResponseWillBeUsed?: (context: CacheResponseWillBeUsedPluginContext) => Response
    readonly requestWillFetch?: (context: RequestWillFetchPluginContext) => Request;
    readonly fetchDidFail?: (context: FetchDidFailPluginContext) => void;
};

interface CacheWillUpdatePluginContext {
    readonly request: Request;
    readonly response: Response;
}

interface CacheDidUpdatePluginContext {
    readonly cacheName: string;
    readonly request: Request;
    readonly oldResponse: Response;
    readonly newResponse: Response;
}

interface CacheResponseWillBeUsedPluginContext {
    readonly cacheName: string;
    readonly request: Request;
    readonly matchOptions: any; // <-- What should this be? `object`?
    readonly cachedResponse: Response;
}

interface RequestWillFetchPluginContext {
    readonly request: Request;
}

interface FetchDidFailPluginContext {
    readonly originalRequest: Request;
    readonly request: Request;
    readonly error: Error;
}
```

Also, had to modify this type:
```ts
type Plugin = BroadcastUpdatePlugin | RangeRequestsPlugin | CacheableResponsePlugin | BackgroundSyncPlugin | ExpirationPlugin | WorkboxPlugin;
```

**Comment by josephliccini** [comment]
I did find another bug in this: 

```ts
type NavigationRouteConstructor = {
    new (handler: HandlerCallback, options: Partial<INavigationRouteOptions>): NavigationRoute;
};
```
should be:
```ts
type NavigationRouteConstructor = {
    new (cachedAssetUrl: string, options: Partial<INavigationRouteOptions>): NavigationRoute;
};
```

**Comment by jeffposnick** [comment]
Hello @wessberg!

First off, apologies for the delay in acting on this PR.

After discussing it with the other current maintainers, we don't feel like we can commit to maintaining these typings over time. We appreciate the work you put into creating them to begin with, but stale typings seem inevitable as we make changes to the codebase given our lack of familiarity with TypeScript.

I'm familiar enough with TypeScript to know that some folks submit "unofficial" `.d.ts` entries to https://definitelytyped.org/, and if you're willing to, I'd encourage you to go that route. We'd be happy to [add a badge](https://definitelytyped.org/pages/badges.html) to our docs linking to your submission for other developers who want to find them.

Would you be willing to go that route?

**Comment by wessberg** [comment]
@josephliccini, I've updated the typings to support returning `Promise<Response` from `cachedResponseWillBeUsed` and `cacheWillUpdate`. Nice catch!

@jeffposnick, that is completely understandable 👍. I'll try to add the typings to DefinitelyTyped instead such that they can be installed from `@types/workbox-sw`.

**Comment by jeffposnick** [comment]
I'm going to close this PR in favor of the DefinitelyTyped approach.

Once there's something published that you want us to link to, pass along the URL.

**Comment by wessberg** [comment]
@jeffposnick, the typings have been published now!
Here's the URL: https://www.npmjs.com/package/@types/workbox-sw

**Pull request closed without merging**
