### PR TITLE
Add install instructions to JSDocs.

### PR DESCRIPTION
**Pull request by jpmedley**
R: @jeffposnick @addyosmani @gauntface 

This seems like the best way to get them into the micro site.

### CODE REVIEW

**Comment by prateekbh** [comment]
@jpmedley  can you check if you are able to generate jsDocs from this?

I was about to open an issue about this as this page appears empty to me
https://workboxjs.org/reference-docs/latest/module-workbox-background-sync.html

**Comment by jpmedley** [comment]
I already did. I visited every page that I touched. Background sync is thin, not because of a bug, but because no one has written it yet. 

I though the install might trigger some discussion so I wanted to submit it as it's own PR. I plan to go through the JSDocs and even them up, but that will be a separte PR.

**Comment by prateekbh** [comment]
cool sure, though every js file in src has its jsDocs

**Comment by jpmedley** [comment]
I mean the stuff in index.js's.

**Pull request merged**
