### PR TITLE
support gtm.js runtime caching

### LINKED ISSUE #1836: Add gtm.js runtime caching
**Library Affected**:
*workbox-google-analytics.*

**Browser & Platform**:
*all browsers.*

**Issue or Feature Request Description**:
*Support runtime caching of gtm.js.*

I would like to add runtime caching for gtm.js because it's responsible of fetching analytics.js so without caching it the offline google analytics will not work if the user starts the app with no connection.

### PR DESCRIPTION
**Pull request by xMokAx**
R: @jeffposnick @philipwalton

Fixes #1836 

*added runtime caching support for gtm.js.*

### CODE REVIEW

**Comment by philipwalton** [comment]
Thanks, can you add tests for your changes? At minimum it'd be nice to have unit tests (which are in [this file](https://github.com/GoogleChrome/workbox/blob/93e414e/test/workbox-google-analytics/node/test-index.mjs)), and if you can also update the [integration tests](https://github.com/GoogleChrome/workbox/blob/93e414e3e431f64edd49bc344a6995943f194866/test/workbox-google-analytics/integration/basic-example.js) that would be great.

You can run the unit tests for just the `workbox-google-analytics` package locally with this command:

```sh
gulp test-node --package workbox-google-analytics
```

And you can run the integration tests for `workbox-google-analytics` with this command

```sh
gulp test-integration --package workbox-google-analytics
```

**Comment by xMokAx** [comment]
Sure, i will just finish something i'm working on right now probably tomorrow then i will see what i can do with tests. Thanks for the tips.

**Comment by xMokAx** [comment]
Sorry for not implementing the tests earlier as i said but i'm on my work right now which is in the middle of Sinai in Egypt and i have the worst internet connection in the world if any connection at all (max download 15 to 20 Kb/s), so i could never finish installing the node modules trying for 3 days and when yarn succeeded to do it it couldn't finish building fresh packages so i tried the following: 
`yarn install --no-lockfile --ignore-scripts`
and then `npm rb` but npm too couldn't rebuild the packages, the internet is just too bad to handle this.
I will be back home at the end of this week probably Thursday and i will start implementing this as soon as possible. Best regards.

**Comment by xMokAx** [comment]
I installed `node_modules` and use `gulp test-node --package workbox-google-analytics` and i got the following error:

```
λ gulp test-node --package workbox-google-analytics
[19:18:25] Using gulpfile D:\ahmed\coding\workbox\gulpfile.js
[19:18:25] Starting 'test-node'...
[19:18:25] Starting 'test-node:clean'...
[19:18:25] Finished 'test-node:clean' after 4.35 ms
[19:18:25] Starting 'test-node:dev'...
[19:18:25] Starting '<anonymous>'...
[Workbox]: Running Node test on test/workbox-google-analytics/node with NODE_ENV 'dev'

> workbox@0.0.0 test D:\ahmed\coding\workbox
> nyc --clean false --require @std/esm --require ./infra/testing/sw-env --silent mocha --timeout 60000 ./infra/testing/auto-stub-logger.mjs "test/workbox-google-analytics/node/**/*.{js,mjs}"

file:///D:/ahmed/coding/workbox/packages/workbox-background-sync/Queue.mjs:1
Error: Cannot find module 'workbox-core/_private/WorkboxError.mjs'
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at Proxy.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at j (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.watch (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/packages/workbox-background-sync/Queue.mjs:1)
    at E (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.run (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/packages/workbox-background-sync/Queue.mjs:1)
    at Module.e (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at J (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at module.exports.r.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module._ (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.d._compile (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.replacementCompile (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at D:\ahmed\coding\workbox\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at qe (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at f (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at p (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at j (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.watch (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/test/workbox-google-analytics/node/test-index.mjs:1)
    at E (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.run (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/test/workbox-google-analytics/node/test-index.mjs:1)
    at Module.e (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at J (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at module.exports.r.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module._ (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.d._compile (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.replacementCompile (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at D:\ahmed\coding\workbox\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at qe (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at f (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at p (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at Proxy.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.t (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at x (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (file:///D:/ahmed/coding/workbox/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (file:///D:/ahmed/coding/workbox/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/mocha/bin/_mocha:637:18)
    at Module.e (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Q (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at module.exports.r.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module._ (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Module.d._compile (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at f (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at p (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at Object..js (file:///D:/ahmed/coding/workbox/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at D:\ahmed\coding\workbox\node_modules\@std\esm\esm.js:1
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at module.exports.t.a (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at Function.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/@std/esm/esm.js:1)
    at runMain (file:///C:/Users/Moka/.node-spawn-wrap-7384-a94962a531f7/node:68:10)
    at Function.<anonymous> (file:///C:/Users/Moka/.node-spawn-wrap-7384-a94962a531f7/node:171:5)
    at Object.<anonymous> (file:///D:/ahmed/coding/workbox/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at C:\Users\Moka\.node-spawn-wrap-7384-a94962a531f7\node:178:8
    at Object.<anonymous> (file:///C:/Users/Moka/.node-spawn-wrap-7384-a94962a531f7/node:181:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workbox@0.0.0 test: `nyc --clean false --require @std/esm --require ./infra/testing/sw-env --silent mocha --timeout 60000 ./infra/testing/auto-stub-logger.mjs "test/workbox-google-analytics/node/**/*.{js,mjs}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the workbox@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Moka\AppData\Roaming\npm-cache\_logs\2019-01-24T17_18_35_139Z-debug.log


[Workbox]: Error 1 returned from npm.cmd run,test,--,test/workbox-google-analytics/node/**/*.{js,mjs}


[19:18:35] '<anonymous>' errored after 9.65 s
[19:18:35] Error: [Workbox Error Msg] 'gulp test-node' discovered errors.
    at runNodeTestSuite (D:\ahmed\coding\workbox\gulp-tasks\test-node.js:35:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[19:18:35] 'test-node:dev' errored after 9.66 s
[19:18:35] 'test-node' errored after 9.67 s
```

Here is the log of this run from `npm` logs:

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\ahmed\\coding\\nodejs\\node.exe',
1 verbose cli   'D:\\ahmed\\coding\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test',
1 verbose cli   '--',
1 verbose cli   'test/workbox-google-analytics/node/**/*.{js,mjs}' ]
2 info using npm@6.4.1
3 info using node@v10.14.1
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle workbox@0.0.0~pretest: workbox@0.0.0
6 info lifecycle workbox@0.0.0~test: workbox@0.0.0
7 verbose lifecycle workbox@0.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle workbox@0.0.0~test: PATH: D:\ahmed\coding\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\ahmed\coding\workbox\node_modules\.bin;D:\ahmed\coding\cmder\bin;D:\ahmed\coding\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\ahmed\coding\cmder\vendor\conemu-maximus5;D:\ahmed\coding\cmder\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell;D:\ahmed\coding\Git\cmd;D:\ahmed\coding\cmder\Cmder.exe;C:\ProgramData\chocolatey\bin;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Python27\python.exe;D:\ahmed\coding\nodejs\;C:\Users\Moka\AppData\Local\Microsoft\WindowsApps;D:\ahmed\coding\nodejs;D:\ahmed\coding\Git\cmd;D:\ahmed\coding\text editors\Microsoft VS Code\bin;D:\ahmed\coding\Heroku\bin;C:\Users\Moka\AppData\Local\.meteor;C:\Program Files\Java\jdk1.8.0_144\bin;D:\ahmed\coding\phantomjs-2.1.1-windows\bin;"C:\WINDOWS\System32;C:\WINDOWS;C:\WINDOWS\System32\Wbem";C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\bash.exe;C:\Users\Moka\AppData\Local\Yarn\Data\global\node_modules\.bin;C:\Python27\python.exe;C:\Users\Moka\AppData\Roaming\npm;C:\Users\Moka\AppData\Roaming\npm;D:\ahmed\coding\Git\usr\bin;D:\ahmed\coding\Git\usr\share\vim\vim74;D:\ahmed\coding\cmder\
9 verbose lifecycle workbox@0.0.0~test: CWD: D:\ahmed\coding\workbox
10 silly lifecycle workbox@0.0.0~test: Args: [ '/d /s /c',
10 silly lifecycle   'nyc --clean false --require @std/esm --require ./infra/testing/sw-env --silent mocha --timeout 60000 ./infra/testing/auto-stub-logger.mjs "test/workbox-google-analytics/node/**/*.{js,mjs}"' ]
11 silly lifecycle workbox@0.0.0~test: Returned: code: 1  signal: null
12 info lifecycle workbox@0.0.0~test: Failed to exec test script
13 verbose stack Error: workbox@0.0.0 test: `nyc --clean false --require @std/esm --require ./infra/testing/sw-env --silent mocha --timeout 60000 ./infra/testing/auto-stub-logger.mjs "test/workbox-google-analytics/node/**/*.{js,mjs}"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\ahmed\coding\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\ahmed\coding\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid workbox@0.0.0
15 verbose cwd D:\ahmed\coding\workbox
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\ahmed\\coding\\nodejs\\node.exe" "D:\\ahmed\\coding\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test" "--" "test/workbox-google-analytics/node/**/*.{js,mjs}"
18 verbose node v10.14.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error workbox@0.0.0 test: `nyc --clean false --require @std/esm --require ./infra/testing/sw-env --silent mocha --timeout 60000 ./infra/testing/auto-stub-logger.mjs "test/workbox-google-analytics/node/**/*.{js,mjs}"`
22 error Exit status 1
23 error Failed at the workbox@0.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```


OS: windows 10
npm: 6.4.1
node: 10.14.1

**Comment by philipwalton** [comment]
Thanks @xMokAx for trying to add these, and sorry you were seeing build issues. I think I'll just merge these into a separate branch that I have access to, then I can address these test issues myself before we merge it into `next`.

**Comment by philipwalton** [comment]
Cherry-picked to https://github.com/GoogleChrome/workbox/pull/1869.

**Pull request closed without merging**
