### PR TITLE
Document skipWaiting message in GenerateSW

### PR DESCRIPTION
**Pull request by jwagner**
R: @jeffposnick @philipwalton

It wasn't very clear from the documentation how `skipWaiting` could be triggered via `postMessage`.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Thanks!

**Review by jeffposnick — CHANGES_REQUESTED** [review]
Would you mind making this change to

https://github.com/GoogleChrome/workbox/blob/9498e9192fd3ed6d60fc54507776d612d3cbde3c/packages/workbox-build/src/generate-sw.js#L171-L174

as well?

**Comment by jwagner** [comment]
Hi @jeffposnick first off, sorry for taking so incredibly long to reply. I added the change to the second location and removed a stray period.

**Review by jeffposnick — APPROVED** [review]
Thank you!

**Pull request merged**
