### PR TITLE
doc(workbox-build): updated link to documentation

### PR DESCRIPTION
**Pull request by ctesniere**
_Description of what's changed/fixed._

- Edit link to documentation for workbox-build

### CODE REVIEW

**Review by Vladisvob — COMMENTED** [review]
#3120

**Review by Vladisvob — APPROVED** [review]
https://ti.to/pwasummit/2022

**Review by Vladisvob — COMMENTED** [review]
Duplicate of #

**Review by Vladisvob — APPROVED** [review]
#3116

**Comment by tropicadri** [comment]
Fixed for v7 in #3313

**Pull request closed without merging**
