### PR TITLE
Add wasm to precache manifest

### PR DESCRIPTION
**Pull request by ArhanChaudhary**
Addresses #3319

I'm not familiar with workbox's codebase, so I may have forgotten to appropriately change something

### CODE REVIEW

**Review by tomayac — APPROVED** [review]
LGTM, approval

@tropicadri, waiting for your review before merging.

**Comment by ArhanChaudhary** [comment]
I think this deserves a bump, this looks like an easy merge.

**Comment by tomayac** [comment]
Agreed. Merged now.

**Comment by tropicadri** [comment]
@ArhanChaudhary Sorry I didn't reply any chance you can create a PR  adding .wasm file examples to the [affected tests](https://github.com/GoogleChrome/workbox/tree/v7/test/workbox-build) for the package? Right now as expected all the tests use .js, .css and .html and I'd like the tests to match updated default.

**Comment by ArhanChaudhary** [comment]
sure, i can soon take a look at that

**Pull request merged**
