### PR TITLE
Fix workbox-broadcast-update link

### PR DESCRIPTION
**Pull request by abraham**
R: @jeffposnick @philipwalton

Current URL 404s.

### CODE REVIEW

**Comment by philipwalton** [comment]
Hmmm, I think the fix for the problem here is our docs site needs to be updated. Specifically the file name of this file as well as some of its titles. @abraham if you're able to make that update and cc me, I can approve and merge.

We also have a TODO to update some of the content there in line with v5 changes: https://github.com/GoogleChrome/workbox/issues/2122

**Comment by philipwalton** [comment]
Hmm, probably makes sense to also add a redirect in this file: https://github.com/google/WebFundamentals/blob/c3570fd9de43d40f91fcf9b3b22e7e64d227538b/src/content/en/tools/_redirects.yaml

**Comment by abraham** [comment]
https://github.com/google/WebFundamentals/pull/8069

**Comment by philipwalton** [comment]
I've published the demos, and the page on developers.google.com/web/ should be updated too, so everything should work now. Thanks!

**Pull request closed without merging**
