### PR TITLE
Add use strict to generate-sw for Node 4 support

### PR DESCRIPTION
**Pull request by MaxLeiter**
R: @jeffposnick @addyosmani @gauntface

Fixes #670

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Signed

**Comment by jeffposnick** [comment]
Thanks for the contribution, @MaxLeiter!

I'd like to move the discussion to #669 in lieu of merging this PR as-is. I know that there are other files inside of `workbox-build` that are using `const` and `let`, so I have a feeling that the change in this PR wouldn't be sufficient. We should talk about addressing it in a more holistic fashion.

**Comment by gauntface** [comment]
Was looking into adding testing for node 4 but it's going to be a pretty big headache since selenium doesn't support anything lower than node 6.

@jeffposnick I'm fine with taking this PR, any other comments from you?

**Comment by jeffposnick** [comment]
👍

**Comment by MaxLeiter** [comment]
any chance of a `1.1.1` release?

**Comment by jeffposnick** [comment]
It's in https://github.com/GoogleChrome/workbox/releases/tag/v1.2.0

**Pull request merged**
